apiVersion: apps/v1
kind: Deployment
metadata:
  name: desktop-deploy
  namespace: magabot-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desktop-page
  template:
    metadata:
      labels:
        app: desktop-page
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: desktop-page
      containers:
      - name: chatbot-app
        image: thepinkpanther96/chatbot-app:latest
        ports:
        - containerPort: 5001
        env:                     
        - name: OPENAI_API_KEY   
          valueFrom:             
            secretKeyRef:        
              name: openai        
              key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: desktop-svc
  namespace: magabot-ns
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  selector:
    app: desktop-page
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001